import { useState } from "react";
import PixelButton from "./ui/PixelButton";
import Input from "./ui/Input";
import Card from "./ui/Card";
import { useAuth } from "../context/AuthContext";

export default function TwoFactorSetup() {
  const { token, user, verifyUser } = useAuth();

  const [qrCode, setQrCode] = useState("");
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSetup = async () => {
    setError("");
    setLoading(true);

    try {
      const response = await fetch("/api/auth/2fa/setup", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.error || "Failed to start 2FA setup");
        return;
      }

      setQrCode(data.qrCode);
    } catch (error) {
      console.error("2FA setup failed:", error);
      setError("Unable to connect to the server");
    } finally {
      setLoading(false);
    }
  };

  const handleConfirm = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    setError("");

    if (!/^\d{6}$/.test(code)) {
      setError("Enter a valid 6-digit code");
      return;
    }

    setLoading(true);

    try {
      const response = await fetch("/api/auth/2fa/confirm", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ code }),
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.error || "Invalid authentication code");
        return;
      }

      await verifyUser();

      setQrCode("");
      setCode("");
    } catch (error) {
      console.error("2FA confirmation failed:", error);
      setError("Unable to connect to the server");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card variant="green" className="p-5">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h2 className="font-pixelify text-pacova-green text-lg uppercase tracking-widest">
            Account Security
          </h2>

          <p className="font-vt323 text-gray-400 text-lg mt-1">
            Protect your Pacova account with an authenticator app.
          </p>
        </div>

        <span
          className={`font-vt323 text-lg uppercase ${
            user?.twoFactorEnabled ? "text-pacova-green" : "text-yellow-400"
          }`}
        >
          {user?.twoFactorEnabled ? "● PROTECTED" : "● NOT PROTECTED"}
        </span>
      </div>

      {user?.twoFactorEnabled ? (
        <div className="border border-pacova-green/30 p-4 rounded">
          <p className="text-pacova-green text-center font-pixelify text-sm uppercase">
            ✓ Two-Factor Authentication Enabled
          </p>

          <p className="font-vt323 text-gray-400 text-center text-lg mt-2">
            Your account requires an authenticator code when you sign in.
          </p>
        </div>
      ) : !qrCode ? (
        <>
          <div className="font-vt323 text-gray-300 text-lg leading-6 mb-4">
            <p>1. Click Enable 2FA.</p>
            <p>2. Scan the QR code with your authenticator app.</p>
            <p>3. Enter the generated 6-digit code.</p>
          </div>

          <PixelButton
            type="button"
            variant="filled-green"
            size="md"
            disabled={loading}
            onClick={handleSetup}
            className="w-full"
          >
            {loading ? "GENERATING..." : "ENABLE 2FA"}
          </PixelButton>
        </>
      ) : (
        <form onSubmit={handleConfirm} className="flex flex-col gap-5">
          <div className="text-center font-vt323">
            <p className="text-pacova-pink text-lg uppercase">
              Step 1 — Scan QR Code
            </p>

            <p className="text-gray-400 text-lg mt-2">
              Open Google Authenticator, Microsoft Authenticator,
              or another TOTP application.
            </p>
          </div>

          <div className="flex justify-center">
            <div className="bg-white p-3">
              <img
                src={qrCode}
                alt="Pacova 2FA QR Code"
                className="w-48 h-48"
              />
            </div>
          </div>

          <div className="text-center font-vt323">
            <p className="text-pacova-pink text-lg uppercase">
              Step 2 — Verify
            </p>

            <p className="text-gray-400 text-lg mt-2">
              Enter the 6-digit code generated by your authenticator.
            </p>
          </div>

          <Input
            label="AUTHENTICATION CODE"
            type="text"
            name="twoFactorCode"
            placeholder="000000"
            value={code}
            onChange={(e) => {
              const value = e.target.value.replace(/\D/g, "");
              setCode(value.slice(0, 6));
            }}
          />

          {error && (
            <p className="font-vt323 text-red-500 text-lg text-center uppercase">
              ⚠️ {error}
            </p>
          )}

          <PixelButton
            type="submit"
            variant="filled-green"
            size="md"
            disabled={loading || code.length !== 6}
            className="w-full"
          >
            {loading ? "VERIFYING..." : "CONFIRM & ENABLE"}
          </PixelButton>

          <button
            type="button"
            onClick={() => {
              setQrCode("");
              setCode("");
              setError("");
            }}
            className="font-vt323 text-gray-400 text-lg underline text-center"
          >
            Cancel setup
          </button>
        </form>
      )}

      {error && !qrCode && (
        <p className="font-vt323 text-red-500 text-lg text-center uppercase">
          ⚠️ {error}
        </p>
      )}
    </Card>
  );
}