import { useState } from "react";
import Button from "./ui/Button";
import Input from "./ui/Input";
import { useAuth } from "../context/AuthContext";

export default function TwoFactorSetup() {
  const { token, user, verifyUser } = useAuth();

  const [qrCode, setQrCode] = useState("");
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSetup = async () => {
    setError("");
    setLoading(true);

    try {
      const response = await fetch("/api/auth/2fa/setup", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.error || "Failed to start 2FA setup");
        return;
      }

      setQrCode(data.qrCode);
    } catch (error) {
      console.error("2FA setup failed:", error);
      setError("Unable to connect to the server");
    } finally {
      setLoading(false);
    }
  };

  const handleConfirm = async (
    e: React.FormEvent<HTMLFormElement>,
  ) => {
    e.preventDefault();

    setError("");

    if (!/^\d{6}$/.test(code)) {
      setError("Enter a valid 6-digit code");
      return;
    }

    setLoading(true);

    try {
      const response = await fetch("/api/auth/2fa/confirm", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          code,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.error || "Invalid authentication code");
        return;
      }

      // Refresh the current user so twoFactorEnabled becomes true.
      await verifyUser();

      setQrCode("");
      setCode("");
    } catch (error) {
      console.error("2FA confirmation failed:", error);
      setError("Unable to connect to the server");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col gap-5 border border-neon-green/50 p-5">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-display text-neon-green text-sm tracking-widest">
            ACCOUNT SECURITY
          </h2>

          <p className="text-xs text-white/60 mt-2">
            Protect your Pacova account with an authenticator app.
          </p>
        </div>

        <span
          className={`text-xs font-display ${
            user?.twoFactorEnabled
              ? "text-neon-green"
              : "text-yellow-400"
          }`}
        >
          {user?.twoFactorEnabled ? "● PROTECTED" : "● NOT PROTECTED"}
        </span>
      </div>

      {user?.twoFactorEnabled ? (
        <div className="border border-neon-green/30 p-4">
          <p className="text-neon-green text-center font-display text-sm">
            ✓ TWO-FACTOR AUTHENTICATION ENABLED
          </p>

          <p className="text-white/60 text-center text-xs mt-2">
            Your account requires an authenticator code when you sign in.
          </p>
        </div>
      ) : !qrCode ? (
        <>
          <div className="text-xs text-white/70 leading-6">
            <p>1. Click Enable 2FA.</p>
            <p>2. Scan the QR code with your authenticator app.</p>
            <p>3. Enter the generated 6-digit code.</p>
          </div>

          <Button
            type="button"
            variant="green"
            styleType="filled"
            disabled={loading}
            onClick={handleSetup}
          >
            {loading ? "GENERATING..." : "ENABLE 2FA"}
          </Button>
        </>
      ) : (
        <form
          onSubmit={handleConfirm}
          className="flex flex-col gap-5"
        >
          <div className="text-center">
            <p className="font-display text-neon-pink text-xs">
              STEP 1 — SCAN QR CODE
            </p>

            <p className="text-white/60 text-xs mt-2">
              Open Google Authenticator, Microsoft Authenticator,
              or another TOTP application.
            </p>
          </div>

          <div className="flex justify-center">
            <div className="bg-white p-3">
              <img
                src={qrCode}
                alt="Pacova 2FA QR Code"
                className="w-48 h-48"
              />
            </div>
          </div>

          <div className="text-center">
            <p className="font-display text-neon-pink text-xs">
              STEP 2 — VERIFY
            </p>

            <p className="text-white/60 text-xs mt-2">
              Enter the 6-digit code generated by your authenticator.
            </p>
          </div>

          <Input
            label="Authentication Code"
            type="text"
            name="twoFactorCode"
            placeholder="000000"
            value={code}
            onChange={(e) => {
              const value = e.target.value.replace(/\D/g, "");
              setCode(value.slice(0, 6));
            }}
          />

          {error && (
            <p className="text-red-500 text-xs text-center">
              {error}
            </p>
          )}

          <Button
            type="submit"
            variant="green"
            styleType="filled"
            disabled={loading || code.length !== 6}
          >
            {loading ? "VERIFYING..." : "CONFIRM & ENABLE"}
          </Button>

          <button
            type="button"
            onClick={() => {
              setQrCode("");
              setCode("");
              setError("");
            }}
            className="text-xs text-white/50 underline text-center"
          >
            Cancel setup
          </button>
        </form>
      )}

      {error && !qrCode && (
        <p className="text-red-500 text-xs text-center">
          {error}
        </p>
      )}
    </div>
  );
}