-- SQL file Postgres automatically runs the first time its container starts.
-- Pacova uses one physical database (pacova), with each service owning its
-- own PostgreSQL schema inside it: auth, user, chat, game.
-- Schemas themselves are created by each service's first Prisma migration,
-- not here — this file only needs to make sure the database exists.